FROM ubuntu:24.04
# FROM srsran/gnb
#FROM uhd:latest


ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y libfftw3-dev \
	libmbedtls-dev \
	libsctp-dev \
	qt5-default \
	libconfig++-dev \
	net-tools \
	nano \
	libtool pkg-config build-essential autoconf \
	automake \
	git  \
	python3 python3-distutils python3-pip python3-apt \
	libzmq3-dev python3-zmq \
	software-properties-common

RUN apt-get update 
RUN add-apt-repository ppa:gnuradio/gnuradio-releases
RUN apt-get update
RUN apt-get install -y gnuradio xterm python3-gi \
	gobject-introspection gir1.2-gtk-3.0 \
	iputils-ping \
	iproute2 libx11-dev iperf \
	cmake \
	redis-server

RUN apt-get update
RUN apt-get install -y libyaml-cpp-dev
	
RUN apt-get update
RUN apt-get install -y libgtest-dev

RUN pip3 install --upgrade pip
RUN pip3 install prometheus_client
RUN pip3 install gym pandas torchvision tensorboard redis debugpy ray gymnasium dm_tree pyarrow typer scikit-image plotly
RUN pip3 install hydra-core==1.1.0
RUN pip3 uninstall -y protobuf
# Install protobuf version 3.20.*
RUN pip3 install protobuf 

#==3.20.*

## copy srsran and Pytorch
RUN mkdir -p /home/EdgeRIC
WORKDIR "/home/EdgeRIC"
COPY . .

COPY setup_netns.sh /opt/EdgeRIC/setup_netns.sh
RUN chmod +x /opt/EdgeRIC/setup_netns.sh
## Compile srsran for enb/epc
RUN apt-get install -y libprotobuf-dev protobuf-compiler

WORKDIR /home/EdgeRIC
CMD [ "/opt/EdgeRIC/setup_netns.sh" ] 
